# Pandas workbook

In this notebook we will review some Pandas tricks. Examples will use the iris dataset from R.A. Fisher, 1936 as provided by the [UCI ML repo](https://archive.ics.uci.edu/dataset/53/iris).

In [9]:
import pandas as pd
pd.options.mode.copy_on_write = True
import numpy as np

In [10]:
# load iris dataset
iris = pd.read_csv('iris.csv')
iris

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# Filtering

Now let's filter for the species being versicolor

In [11]:
iris[iris['species'] == 'versicolor'].info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 50 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  50 non-null     float64
 1   sepal_width   50 non-null     float64
 2   petal_length  50 non-null     float64
 3   petal_width   50 non-null     float64
 4   species       50 non-null     object
dtypes: float64(4), object(1)
memory usage: 2.3+ KB

In [12]:
iris[iris['species'].isin(['versicolor', 'setosa'])].info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  100 non-null    float64
 1   sepal_width   100 non-null    float64
 2   petal_length  100 non-null    float64
 3   petal_width   100 non-null    float64
 4   species       100 non-null    object
dtypes: float64(4), object(1)
memory usage: 4.7+ KB

Exercise: How many observations have sepal length in the upper 50% quantile and petal width greater than 2?

In [13]:
thresh = np.quantile(iris['sepal_length'], 0.5)
len(iris[(iris['sepal_length'] > thresh) & (iris['petal_width']>2)])

22

# Selecting

We may want to select only a subset of columns

In [14]:
iris[['sepal_length', 'species']]

     sepal_length    species
0             5.1     setosa
1             4.9     setosa
2             4.7     setosa
3             4.6     setosa
4             5.0     setosa
..            ...        ...
145           6.7  virginica
146           6.3  virginica
147           6.5  virginica
148           6.2  virginica
149           5.9  virginica

[150 rows x 2 columns]

In [15]:
# select all columns except sepal length and species
iris[iris.columns.difference(['sepal_length', 'species'])]

     petal_length  petal_width  sepal_width
0             1.4          0.2          3.5
1             1.4          0.2          3.0
2             1.3          0.2          3.2
3             1.5          0.2          3.1
4             1.4          0.2          3.6
..            ...          ...          ...
145           5.2          2.3          3.0
146           5.0          1.9          2.5
147           5.2          2.0          3.0
148           5.4          2.3          3.4
149           5.1          1.8          3.0

[150 rows x 3 columns]

Exercise: How would you select only the columns containing the word "length", without explicitly writing them out? (in a bigger dataset where there may be dozens of columns containing "length", you wouldn't want to type them all out).

In [16]:
print(iris.columns.str.contains('length'))
print(iris.columns[iris.columns.str.contains('length')])
iris[iris.columns[iris.columns.str.contains('length')]]

[ True False  True False False]
Index(['sepal_length', 'petal_length'], dtype='object')

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

We can also select columns of only certain types

In [17]:
# select only numeric columns
iris.select_dtypes(include='number')

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

Let's make a new dataframe with a new column `sepal_sum`, which holds the sum of `sepal_length` and `sepal_width` for `versicolor` flowers.

In [18]:
iris_vc = iris[iris['species'] == 'versicolor']
iris_vc['sepal_sum'] = iris_vc['sepal_length'] + iris_vc['sepal_width']
iris_vc.head()

,sepal_length,sepal_width,petal_length,petal_width,species,sepal_sum
50,7.0,3.2,4.7,1.4,versicolor,10.2
51,6.4,3.2,4.5,1.5,versicolor,9.6
52,6.9,3.1,4.9,1.5,versicolor,10.0
53,5.5,2.3,4.0,1.3,versicolor,7.8
54,6.5,2.8,4.6,1.5,versicolor,9.3

In [19]:
# multiply every column containing "sepal" by 2
iris_new = iris.copy()
iris_new.loc[:, iris_new.columns.str.contains('sepal')] *= 2
iris_new.head()

   sepal_length  sepal_width  petal_length  petal_width species
0          10.2          7.0           1.4          0.2  setosa
1           9.8          6.0           1.4          0.2  setosa
2           9.4          6.4           1.3          0.2  setosa
3           9.2          6.2           1.5          0.2  setosa
4          10.0          7.2           1.4          0.2  setosa

# `groupby`

In [20]:
iris.groupby('species').mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [21]:
iris.groupby('species').apply(lambda x: x.max() - x.min())

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               1.5          2.1           0.9          0.5
versicolor           2.1          1.4           2.1          0.8
virginica            3.0          1.6           2.4          1.1

Exercise: For each species, randomly select half of the observations and compute the 0.25 quantile for each feature (i.e., sepal_length, sepal_width, petal_length, and petal_width). Hint: see `DataFrame.sample()`

In [22]:
iris.groupby('species').sample(25).groupby('species').quantile(0.25)

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               4.8          3.2           1.3          0.2
versicolor           5.6          2.5           4.0          1.3
virginica            6.2          2.8           5.1          1.8

# `sort_values`

In [23]:
iris.sort_values('petal_length')

     sepal_length  sepal_width  petal_length  petal_width    species
22            4.6          3.6           1.0          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
35            5.0          3.2           1.2          0.2     setosa
36            5.5          3.5           1.3          0.2     setosa
..            ...          ...           ...          ...        ...
131           7.9          3.8           6.4          2.0  virginica
105           7.6          3.0           6.6          2.1  virginica
117           7.7          3.8           6.7          2.2  virginica
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica

[150 rows x 5 columns]

In [24]:
iris.sort_values(['petal_length', 'sepal_width'], ascending=[False, True])

     sepal_length  sepal_width  petal_length  petal_width    species
118           7.7          2.6           6.9          2.3  virginica
122           7.7          2.8           6.7          2.0  virginica
117           7.7          3.8           6.7          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
131           7.9          3.8           6.4          2.0  virginica
..            ...          ...           ...          ...        ...
16            5.4          3.9           1.3          0.4     setosa
35            5.0          3.2           1.2          0.2     setosa
14            5.8          4.0           1.2          0.2     setosa
13            4.3          3.0           1.1          0.1     setosa
22            4.6          3.6           1.0          0.2     setosa

[150 rows x 5 columns]

Exercise: For each species, only keep the observations with the largest 10 sepal lengths. Then, sort the rows in order of decreasing sepal length. Hint: can you do this using an `apply` with a `group_by`?

In [25]:
iris.groupby('species').apply(lambda x: x.sort_values('sepal_length', ascending=False).head(10), include_groups=False)
iris.groupby('species').apply(lambda x: x.nlargest(10, 'sepal_length'), include_groups=False)

                sepal_length  sepal_width  petal_length  petal_width
species
setosa     14            5.8          4.0           1.2          0.2
           15            5.7          4.4           1.5          0.4
           18            5.7          3.8           1.7          0.3
           33            5.5          4.2           1.4          0.2
           36            5.5          3.5           1.3          0.2
           5             5.4          3.9           1.7          0.4
           10            5.4          3.7           1.5          0.2
           16            5.4          3.9           1.3          0.4
           20            5.4          3.4           1.7          0.2
           31            5.4          3.4           1.5          0.4
versicolor 50            7.0          3.2           4.7          1.4
           52            6.9          3.1           4.9          1.5
           76            6.8          2.8           4.8          1.4
           65            6.7          3.1           4.4          1.4
           77            6.7          3.0           5.0          1.7
           86            6.7          3.1           4.7          1.5
           58            6.6          2.9           4.6          1.3
           75            6.6          3.0           4.4          1.4
           54            6.5          2.8           4.6          1.5
           51            6.4          3.2           4.5          1.5
virginica  131           7.9          3.8           6.4          2.0
           117           7.7          3.8           6.7          2.2
           118           7.7          2.6           6.9          2.3
           122           7.7          2.8           6.7          2.0
           135           7.7          3.0           6.1          2.3
           105           7.6          3.0           6.6          2.1
           130           7.4          2.8           6.1          1.9
           107           7.3          2.9           6.3          1.8
           109           7.2          3.6           6.1          2.5
           125           7.2          3.2           6.0          1.8

# Merges (joins)

Let's make a couple dataframes to play around with merges (aka joins)

In [26]:
import string
lowercase_data = pd.DataFrame(dict(id = range(2,7), lower = list(string.ascii_lowercase[1:6])))
lowercase_data

   id lower
0   2     b
1   3     c
2   4     d
3   5     e
4   6     f

In [27]:
uppercase_data = pd.DataFrame(dict(id = range(1,6), upper = list(string.ascii_uppercase[0:5])))
uppercase_data

   id upper
0   1     A
1   2     B
2   3     C
3   4     D
4   5     E

We can use these to demonstrate all four kinds of joins. In each case, the DataFrames are automatically joined on the common column `id`

In [28]:
pd.merge(lowercase_data, uppercase_data, how='inner')

   id lower upper
0   2     b     B
1   3     c     C
2   4     d     D
3   5     e     E

In [29]:
pd.merge(lowercase_data, uppercase_data, how='left')

   id lower upper
0   2     b     B
1   3     c     C
2   4     d     D
3   5     e     E
4   6     f   NaN

In [30]:
pd.merge(lowercase_data, uppercase_data, how='right')

   id lower upper
0   1   NaN     A
1   2     b     B
2   3     c     C
3   4     d     D
4   5     e     E

In [31]:
pd.merge(lowercase_data, uppercase_data, how='outer')

   id lower upper
0   1   NaN     A
1   2     b     B
2   3     c     C
3   4     d     D
4   5     e     E
5   6     f   NaN

# Data cleaning

Lat's make a DataFrame which is rather messy.

In [32]:
iris_messy = pd.concat((iris, iris.sample(n=50, replace=True))).sample(frac=1).reset_index(drop=True)
iris_messy.loc[np.random.sample(iris_messy.shape[0]) < 0.1,'species'] = pd.NA
iris_messy

     sepal_length  sepal_width  petal_length  petal_width     species
0             6.0          2.2           4.0          1.0  versicolor
1             5.1          2.5           3.0          1.1  versicolor
2             6.0          2.2           4.0          1.0  versicolor
3             4.9          3.1           1.5          0.1        <NA>
4             6.0          2.7           5.1          1.6  versicolor
..            ...          ...           ...          ...         ...
195           5.1          3.8           1.9          0.4      setosa
196           4.8          3.4           1.9          0.2      setosa
197           5.5          2.4           3.8          1.1        <NA>
198           4.6          3.1           1.5          0.2      setosa
199           6.7          3.3           5.7          2.5   virginica

[200 rows x 5 columns]

Exercise: clean up `iris_messy` to remove duplicate rows and rows with an NA value in `species`.

In [33]:
# clean up iris_messy
iris_messy = iris_messy.drop_duplicates()
iris_messy = iris_messy.dropna(subset=['species'])
iris_messy

     sepal_length  sepal_width  petal_length  petal_width     species
0             6.0          2.2           4.0          1.0  versicolor
1             5.1          2.5           3.0          1.1  versicolor
4             6.0          2.7           5.1          1.6  versicolor
5             5.5          2.6           4.4          1.2  versicolor
6             6.7          3.3           5.7          2.5   virginica
..            ...          ...           ...          ...         ...
192           5.5          3.5           1.3          0.2      setosa
194           6.0          2.9           4.5          1.5  versicolor
195           5.1          3.8           1.9          0.4      setosa
196           4.8          3.4           1.9          0.2      setosa
198           4.6          3.1           1.5          0.2      setosa

[139 rows x 5 columns]